version: '3'
services:
  app-2:
    build: .
    ports:
      - "8088:8080"
    volumes:
      - C:/tmp/output:/app/output
    environment:
      - SPRING_PROFILE=docker  # Активируем профиль для Docker
