spring:
  application:
    name: github-reader

github:
  token: ${GITHUB_TOKEN}

  includePatterns:
#    - "**/*.md"
#    - "*.md"           # Добавлено для файлов в корне
    - "**/*.txt"
    - "**/*.xml"
    - "*.xml"
    - "**/*.java"
    - "**/*.jte"
    - "**/*.yaml"
    - "*.yaml"
    - "**/*.yml"
    - "*.yml"
    - "**/*.graphqls"
    - "**/*.properties"

  excludePatterns:
    - ".mvn/**"
    - ".idea/**"
    - ".gigaide/**"
    - "target/**"
    - ".gitignore"
    - ".gitattributes"
    - "mvnw"
    - "mvnw.cmd"

singleFilePath: "output/all_contents.txt"  # Путь к файлу для всего контента

directory:
  defaultPath: "E:\\projects\\java\\p3_tariff_calculator"  # Путь по умолчанию