spring:
  application:
    name: github-reader
  profiles:
    active: ${SPRING_PROFILE:default}  # По умолчанию "default", можно переопределить через переменную окружения

github:
  token: ${GITHUB_TOKEN}

  includePatterns:
#    - "**/*.md"
#    - "*.md"           # Добавлено для файлов в корне
    - "**/*.txt"
    - "**/*.xml"
    - "*.xml"
    - "**/*.java"
    - "**/*.jte"
    - "**/*.yaml"
    - "*.yaml"
    - "**/*.yml"
    - "*.yml"
    - "**/*.graphqls"
    - "**/*.properties"

  excludePatterns:
    - ".mvn/**"
    - ".idea/**"
    - ".gigaide/**"
    - "target/**"
    - ".gitignore"
    - ".gitattributes"
    - "mvnw"
    - "mvnw.cmd"

---
spring:
  config:
    activate:
      on-profile: default  # Профиль для локального запуска на Windows
file:
  output:
    path: "C:\\tmp\\output\\"  # ?Путь для Windows с экранированными слэшами
  name: "all_contents_from_"

---
spring:
  config:
    activate:
      on-profile: docker  # Профиль для запуска в Docker
file:
  output:
    path: "/app/output/"  # Путь для Docker (Linux-стиль)
  name: "all_contents_from_"
